// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlt1xoytofn3syEXtpIs1Pz1ZWvqrNakQ',
    appId: '1:688332445768:web:4f06e31b58f5e8363f607d',
    messagingSenderId: '688332445768',
    projectId: 'elue-store',
    authDomain: 'elue-store.firebaseapp.com',
    storageBucket: 'elue-store.firebasestorage.app',
    measurementId: 'G-V3DFM20V5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDud57C-PFVHcydXeLzH6ao2I108xBlWUA',
    appId: '1:688332445768:android:89ff8d237cde6dca3f607d',
    messagingSenderId: '688332445768',
    projectId: 'elue-store',
    storageBucket: 'elue-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJu_KGWJ2WotBry9b94Vbri0M9QiciCIY',
    appId: '1:688332445768:ios:de2e87c82e84d8cd3f607d',
    messagingSenderId: '688332445768',
    projectId: 'elue-store',
    storageBucket: 'elue-store.firebasestorage.app',
    iosBundleId: 'com.example.cwtEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJu_KGWJ2WotBry9b94Vbri0M9QiciCIY',
    appId: '1:688332445768:ios:de2e87c82e84d8cd3f607d',
    messagingSenderId: '688332445768',
    projectId: 'elue-store',
    storageBucket: 'elue-store.firebasestorage.app',
    iosBundleId: 'com.example.cwtEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlt1xoytofn3syEXtpIs1Pz1ZWvqrNakQ',
    appId: '1:688332445768:web:83d61e3bc909bbca3f607d',
    messagingSenderId: '688332445768',
    projectId: 'elue-store',
    authDomain: 'elue-store.firebaseapp.com',
    storageBucket: 'elue-store.firebasestorage.app',
    measurementId: 'G-07R29N1JQ9',
  );
}
